HubSpot Setup — FractPath Marketing (MVP)

This document describes how to configure HubSpot to receive and store leads generated from the FractPath marketing calculator (fractpath.com), in alignment with the marketing site architecture and calculator payloads.

This setup supports:

persona-based lead capture (Homeowner / Buyer / Realtor)

scenario modeling summaries

future automation (email follow-ups, CRM workflows)

auditability of marketing interactions

1. Create a HubSpot Private App (API Access)

FractPath uses a HubSpot Private App to securely send lead data from the marketing site to HubSpot.

Steps

Log into HubSpot

Go to Settings

Navigate to:

Integrations → Private Apps


Click Create private app

App details

Name: FractPath Marketing

Description: Lead capture from FractPath marketing calculator

Required scopes (minimum)

Enable the following scopes:

crm.objects.contacts.read

crm.objects.contacts.write

(Do not enable more scopes than necessary.)

Create the app

Copy the Access Token

Where to store it

Add the token to Vercel → Project Settings → Environment Variables:

HUBSPOT_ACCESS_TOKEN=your_private_app_token_here


⚠️ Never commit this token to GitHub.

2. Create Custom Contact Properties in HubSpot

All FractPath marketing leads are stored as Contacts in HubSpot.

You must create the following custom contact properties so the API payload can be stored without errors.

Navigation

In HubSpot:

Settings → Properties → Contact properties → Create property

3. Required Custom Properties (Create Exactly As Listed)

⚠️ Property internal names must match exactly (case-sensitive)

A) Persona + source tracking
fp_persona

Label: FractPath Persona

Internal name: fp_persona

Type: Single-line text

Description: Persona selected on FractPath calculator (homeowner, buyer, realtor)

fp_source

Label: FractPath Source

Internal name: fp_source

Type: Single-line text

Description: Lead source identifier (e.g., homepage_calculator)

B) Scenario summary + structured data
fp_deal_summary

Label: FractPath Deal Summary

Internal name: fp_deal_summary

Type: Multi-line text

Description: Human-readable scenario summary generated by calculator

fp_scenario_inputs_json

Label: FractPath Scenario Inputs (JSON)

Internal name: fp_scenario_inputs_json

Type: Multi-line text

Description: Raw numeric inputs from calculator (JSON string)

fp_scenario_outputs_json

Label: FractPath Scenario Outputs (JSON)

Internal name: fp_scenario_outputs_json

Type: Multi-line text

Description: Computed outputs including equity, payouts, floor/cap effects (JSON string)

fp_last_scenario_at

Label: FractPath Last Scenario Modeled At

Internal name: fp_last_scenario_at

Type: Date & Time

Description: Timestamp of most recent calculator interaction

C) Optional numeric properties (recommended for reporting)

These are not strictly required for MVP, but strongly recommended so HubSpot lists and filters work cleanly.

fp_property_value

Label: Property Value

Internal name: fp_property_value

Type: Number

Description: Property value used in scenario

fp_upfront

Label: Upfront Contribution

Internal name: fp_upfront

Type: Number

Description: Upfront contribution modeled

fp_monthly

Label: Monthly Contribution

Internal name: fp_monthly

Type: Number

Description: Monthly contribution modeled

fp_horizon_years

Label: Horizon (Years)

Internal name: fp_horizon_years

Type: Number

Description: Scenario horizon in years

4. How These Properties Are Used (Important Context)

When a user submits their email to reveal calculator results:

A HubSpot contact is created or updated by email

The calculator sends:

persona

scenario inputs (raw numbers)

scenario outputs (equity %, payouts, floor/cap effects)

a conservative deal summary sentence

If the same email is used again:

the contact is updated, not duplicated

fp_last_scenario_at is refreshed

This design ensures:

no duplicate leads

auditable scenario history

clean handoff to future secure portal onboarding

5. Alignment With Webflow (if used previously)

If Webflow forms were previously used:

Do not rely on Webflow → HubSpot form sync for calculator leads

The calculator uses a custom API route (/api/lead) instead

This avoids losing structured scenario data

Webflow can still be used for:

static content

legacy pages

non-calculator email capture (if needed)

6. Validation Checklist (after setup)

After completing setup, verify:

 Submitting calculator email creates a HubSpot contact

 fp_persona is populated correctly

 fp_deal_summary contains readable text

 JSON fields are populated and readable

 Submitting the same email twice updates the same contact

 No API errors appear in Vercel logs

7. Future-proofing (No action now)

This setup intentionally leaves room for:

lifecycle stages

deal objects

portal onboarding events

contract execution workflows

No schema migration will be required later if these properties are created correctly now.
